[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vytal"
authors = [{name = "Sritan Motati", email = "sritanmotati@gmail.com"}]
dynamic = ["version", "description"]
